CORE_BACKEND_HOST: localhost
CORE_BACKEND_PORT: 8081

spring:
  security:
    password:
      encoding:
        bcrypt:
          strength: 10
  cloud:
    gateway:
      routes:
        - id: proxy-all-to-core-backend
          uri: http://localhost:8081
          predicates:
            - Path=/**
          filters:
            - PreserveHostHeader
