spring:
  security:
    password:
      encoding:
        bcrypt:
          strength: 10
  cloud:
    gateway:
      routes:
        - id: core-backend
          uri: http://localhost:8081
          predicates:
            - Path=/**
