spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_booster_db?currentSchema=notification_service}

reminder:
  cron:
    expression: ${REMINDER_CRON_EXPRESSION:0 0 10 ? * SUN}